; Arduino ESP32

[platformio]
src_dir = src
include_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_ldf_mode = deep
lib_deps = https://github.com/adafruit/Adafruit_VL53L0X

; [env:esp32s3cam]
; platform = espressif32 @ ^6.6.0
; board = esp32-s3-devkitc-1
; framework = arduino

; monitor_speed = 115200
; upload_speed = 460800
; lib_ldf_mode = deep

; build_flags =
;     -DARDUINO_USB_MODE=1
;     -DARDUINO_USB_CDC_ON_BOOT=1
;     -DUSE_OV2640